apiVersion: v1
kind: Pod
metadata:
  name: demo-cs
  labels:
    app: demo-cs
spec:
  serviceAccountName: cockroachdb
  initContainers:
  # The init-certs container sends a certificate signing request to the
  # kubernetes cluster.
  # You can see pending requests using: kubectl get csr
  # CSRs can be approved using:         kubectl certificate approve <csr name>
  #
  # In addition to the client certificate and key, the init-certs entrypoint will symlink
  # the cluster CA to the certs directory.
  - name: init-certs
    image: cockroachdb/cockroach-k8s-request-cert:0.4
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/ash"
    - "-ecx"
    - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client -user=maxroach -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
  containers:
    - name: cockroach-csharp-loader
      image: cockroach-csharp-loader
      imagePullPolicy: Never
      volumeMounts:
      - name: client-certs
        mountPath: /cockroach-certs
      env:
        - name: COCKROACH_HOST
          value: "cockroachdb-public.default.svc.cluster.local"
      command:
      - sleep
      - "2147483648" # 2^31
      # This pod isn't doing anything important, so don't bother waiting to terminate it.
      resources:
        # requests:
        #   cpu: "1"
        #   memory: "128Mi"
        limits:
          cpu: "1"
          memory: "128Mi"
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    emptyDir: {}
